export * from "./Background";
export * from "./Header";
export * from "./MainPage/Hero";
export * from "./MainPage/Section1";
export * from "./MainPage/Section2";
export * from "./MainPage/Section3";
export * from "./MainPage/Section4";
export * from "./MainPage/Section5";
export * from "./Footer";
