export * from "./Background";
export * from "./Header";
export * from "./mainPage/Hero";
export * from "./mainPage/Section1";
export * from "./mainPage/Section2";
export * from "./mainPage/Section3";
export * from "./mainPage/Section4";
export * from "./mainPage/Section5";
export * from "./Footer";
