export * from "./Header/Header";
export * from "./Hero/Hero";
export * from "./Section1/Section1";
export * from "./Section2/Section2";
export * from "./Section3/Section3";
export * from "./Section4/Section4";
export * from "./Section5/Section5";
export * from "./Footer";
export * from "./Background";
